apiVersion: v1
kind: Service
metadata:
    name: sample-python-svc
spec:
    ports:
    - name: python-app1-service
      targetPort: 5001
      port: 5200
      nodePort: 30275
      protocol: TCP
    selector:
      app: python-app1
    type: NodePort